### ISSUE TITLE
[199] Domanda 58 - pizza da 10000 bitcoin

### ISSUE THREAD

**Issue by alessandro-aglietti** [bitcoin-dalla-teoria-alla-pratica/errata-corrige-e-sorgente-esempi#10]
*Che tipo di segnalazione stai facendo?*
- [ ] Errore
- [X] Modifica

*Quale e' la versione della domanda che proponi?*
Dove posso vedere la transazione della pizza **da 10000 bitcoin**?

**Comment by Barno** [comment]
presa in consegna ITA
