### ISSUE TITLE
[199] Domanda 90 - seed phrase femminile?

### ISSUE THREAD

**Issue by alessandro-aglietti** [bitcoin-dalla-teoria-alla-pratica/errata-corrige-e-sorgente-esempi#11]
*Che tipo di segnalazione stai facendo?*
- [ ] Errore
- [X] Modifica

*Quale e' la versione della domanda che proponi?*
Come vengono scelte le parole **della** seed phrase?

**Comment by Barno** [comment]
doppia issue
