### ISSUE TITLE
[199] Domanda 109 - struttura domanda

### ISSUE THREAD

**Issue by alessandro-aglietti** [bitcoin-dalla-teoria-alla-pratica/errata-corrige-e-sorgente-esempi#12]
*Che tipo di segnalazione stai facendo?*
- [ ] Errore
- [X] Modifica

*Quale e' la versione della domanda che proponi?*
Bitcoin core, di default, dove salva la blockchain?

**Comment by Barno** [comment]
Presa in carico ITA
