### ISSUE TITLE
[199] Domanda 118 - lo hash?

### ISSUE THREAD

**Issue by alessandro-aglietti** [bitcoin-dalla-teoria-alla-pratica/errata-corrige-e-sorgente-esempi#13]
*Che tipo di segnalazione stai facendo?*
- [ ] Errore
- [X] Modifica

*Quale e' la versione della domanda che proponi?*
Come si calcola l'hash di un blocco?

**Comment by Barno** [comment]
Qui era intesa come si calcola un hash del blocco, cioè non è detto che sia l'hash voluto. Un tentativo di hash che va a risolvere la PoW.
Suggerisci lo stesso la modifica?

**Comment by Barno** [comment]
no fix
