### ISSUE TITLE
[199] Domanda 128 - fullnode meglio di nodo?

### ISSUE THREAD

**Issue by alessandro-aglietti** [bitcoin-dalla-teoria-alla-pratica/errata-corrige-e-sorgente-esempi#15]
*Che tipo di segnalazione stai facendo?*
- [ ] Errore
- [X] Modifica

*Quale e' la versione della domanda che proponi?*
Che differenza c'e' fra **fullnode** e miner?

**Comment by Barno** [comment]
anche un SPV verifica le tx
