### ISSUE TITLE
[199] Domanda 160 - "zero" e trascrittura

### ISSUE THREAD

**Issue by alessandro-aglietti** [bitcoin-dalla-teoria-alla-pratica/errata-corrige-e-sorgente-esempi#16]
*Che tipo di segnalazione stai facendo?*
- [ ] Errore
- [X] Modifica

*Quale e' la versione della risposta che proponi?*
[...] come ad esempio lo 0, "zero", e [...] errori di **tra**scrittura.

**Comment by Barno** [comment]
presa in carico ITA
