### ISSUE TITLE
[199] Domanda 31 - aggiungere link a delibera agenzia entrate

### ISSUE THREAD

**Issue by alessandro-aglietti** [bitcoin-dalla-teoria-alla-pratica/errata-corrige-e-sorgente-esempi#33]
*Che tipo di segnalazione stai facendo?*
- [ ] Errore
- [X] Modifica

https://drive.google.com/file/d/0B9vhVI44DUKKM0RFSjJPdUZJTDA/view?usp=sharing

**Comment by Barno** [comment]
presa in Carico ITA
