### ISSUE TITLE
[199] Domanda 56 - ++enfasi

### ISSUE THREAD

**Issue by alessandro-aglietti** [bitcoin-dalla-teoria-alla-pratica/errata-corrige-e-sorgente-esempi#43]
*Che tipo di segnalazione stai facendo?*
- [ ] Errore
- [X] Modifica

*Quale e' la versione della risposta che proponi?*
[...] necessita'**.** **Perderai** [...] **Per sempre**. **Da grandi poteri derivano grandi responsabilita'.**

**Comment by Barno** [comment]
presa in carico ITA

**Comment by Barno** [comment]
preso in ENG
