### ISSUE TITLE
[199] Domanda 59 - sorelle > sorellastre

### ISSUE THREAD

**Issue by alessandro-aglietti** [bitcoin-dalla-teoria-alla-pratica/errata-corrige-e-sorgente-esempi#45]
*Che tipo di segnalazione stai facendo?*
- [ ] Errore
- [X] Modifica

*Quale e' la versione della risposta che proponi?*
[...] con**, in alcuni casi,** altre [...]

**Comment by Barno** [comment]
presa in carico ITA

**Comment by Barno** [comment]
presa in carico ENG
