### ISSUE TITLE
[199] Domanda 71 - hash/sec

### ISSUE THREAD

**Issue by alessandro-aglietti** [bitcoin-dalla-teoria-alla-pratica/errata-corrige-e-sorgente-esempi#48]
*Che tipo di segnalazione stai facendo?*
- [ ] Errore
- [X] Modifica

*Quale e' la versione della risposta che proponi?*
[...] **la quantita' di hash al secondo che la rete e' in grado di sostenere.**

**Comment by Barno** [comment]
presa in carico ITA

**Comment by Barno** [comment]
ENG
