### ISSUE TITLE
[199] Domanda 81 - itagliash

### ISSUE THREAD

**Issue by alessandro-aglietti** [bitcoin-dalla-teoria-alla-pratica/errata-corrige-e-sorgente-esempi#49]
*Che tipo di segnalazione stai facendo?*
- [ ] Errore
- [X] Modifica

*Quale e' la versione della risposta che proponi?*
[...] creando l'hash **che viene usato come block header** nel [...]

**Comment by Barno** [comment]
Presa in carico ITA.

In eng Check anche block header VS header block

**Comment by Barno** [comment]
ENG
