### ISSUE TITLE
[199] Domanda 82 - levare "e per motivi di sicurezza"

### ISSUE THREAD

**Issue by alessandro-aglietti** [bitcoin-dalla-teoria-alla-pratica/errata-corrige-e-sorgente-esempi#50]
*Che tipo di segnalazione stai facendo?*
- [ ] Errore
- [X] Modifica

Secondo me la scelta dei dieci minuti e' presa un po' 80/20
_Ten minutes was specifically chosen by Satoshi as a tradeoff between first confirmation time and the amount of work wasted due to chain splits_

https://bitcoin.stackexchange.com/questions/1863/why-was-the-target-block-time-chosen-to-be-10-minutes

**Comment by Barno** [comment]
dopo una ricerca, è giusta anche per motivi di sicurezza
