### ISSUE TITLE
[199] Domanda 84 - il reward e' il reward

### ISSUE THREAD

**Issue by alessandro-aglietti** [bitcoin-dalla-teoria-alla-pratica/errata-corrige-e-sorgente-esempi#51]
*Che tipo di segnalazione stai facendo?*
- [ ] Errore
- [X] Modifica

*Quale e' la versione della risposta che proponi?*
Togliere tutto e lasciare solo _Oggi, 2019, il reward e' di 12.5 bitcoin a blocco._
Le fee penso che non si possano considerare reward.

**Comment by Barno** [comment]
Presa in carico ITA

**Comment by Barno** [comment]
Presa in carico ENG
