### ISSUE TITLE
[199] Domanda 86 - fee + reward

### ISSUE THREAD

**Issue by alessandro-aglietti** [bitcoin-dalla-teoria-alla-pratica/errata-corrige-e-sorgente-esempi#52]
*Che tipo di segnalazione stai facendo?*
- [ ] Errore
- [X] Modifica

*Quale e' la versione della domanda che proponi?*
A chi sono destinate le fee?

*Quale e' la versione della risposta che proponi?*
**Le fee si sommano al** reward [...]

**Comment by Barno** [comment]
presa in carico in ITA

**Comment by Barno** [comment]
presa in carico in ENG
