### ISSUE TITLE
[199] Domanda 92 - aggiungere link a blocco 0

### ISSUE THREAD

**Issue by alessandro-aglietti** [bitcoin-dalla-teoria-alla-pratica/errata-corrige-e-sorgente-esempi#54]
*Che tipo di segnalazione stai facendo?*
- [ ] Errore
- [X] Modifica

**Comment by Barno** [comment]
presa in carico in ITA (http://bit.ly/2Sju4au)

**Comment by Barno** [comment]
presa in carico in ENG (http://bit.ly/2Sju4au)
