### ISSUE TITLE
[199] Domanda 126 - la privacy merita' di +

### ISSUE THREAD

**Issue by alessandro-aglietti** [bitcoin-dalla-teoria-alla-pratica/errata-corrige-e-sorgente-esempi#61]
*Che tipo di segnalazione stai facendo?*
- [ ] Errore
- [X] Modifica

*Quale e' la versione della risposta che proponi?*
Per rendere difficile aggregare i mittenti e destinatari delle TX migliorandone la privacy.

**Comment by Barno** [comment]
> Per rendere difficile aggregare i mittenti e destinatari delle transazioni, migliorandone la privacy.

**Comment by Barno** [comment]
presa in carico in ita
