### ISSUE TITLE
[199] Domanda 138 - monetine gratis

### ISSUE THREAD

**Issue by alessandro-aglietti** [bitcoin-dalla-teoria-alla-pratica/errata-corrige-e-sorgente-esempi#65]
*Che tipo di segnalazione stai facendo?*
- [ ] Errore
- [X] Modifica

*Quale e' la versione della domanda che proponi?*
delle **monetine gratis**

*Quale e' la versione della risposta che proponi?*
[...] criptovalute nella nuova blockchain
[...] si forma **utilizzando anche UTXO antecedenti al fork**

**Comment by Barno** [comment]
presa in carico ita

**Comment by Barno** [comment]
presa in carico eng
