### ISSUE TITLE
[199] Domanda 143 - i sassi si lanciano

### ISSUE THREAD

**Issue by alessandro-aglietti** [bitcoin-dalla-teoria-alla-pratica/errata-corrige-e-sorgente-esempi#67]
*Che tipo di segnalazione stai facendo?*
- [ ] Errore
- [X] Modifica

*Quale e' la versione della risposta che proponi?*
lanciare > eseguire
[...] con **il nodo remoto**.

**Comment by Barno** [comment]
presa in carico in ita

**Comment by Barno** [comment]
presa in carico in eng
