### ISSUE TITLE
[199] Domanda 146 - *le UTXO*

### ISSUE THREAD

**Issue by alessandro-aglietti** [bitcoin-dalla-teoria-alla-pratica/errata-corrige-e-sorgente-esempi#68]
*Che tipo di segnalazione stai facendo?*
- [ ] Errore
- [X] Modifica

*Quale e' la versione della risposta che proponi?*
[..] e' **salvato/scritto** nell'input[...]

**Comment by Barno** [comment]
>Scritto.

presa in carico ita
