### ISSUE TITLE
[199] Domanda 164 - [...]. Ed il vertice del merkle tree

### ISSUE THREAD

**Issue by alessandro-aglietti** [bitcoin-dalla-teoria-alla-pratica/errata-corrige-e-sorgente-esempi#74]
*Che tipo di segnalazione stai facendo?*
- [ ] Errore
- [X] Modifica

**Comment by Barno** [comment]
> È l’impronta digitale di tutte le transazioni contenute nel blocco. Il merkle root rappresenta il vertice del merkle tree.

**Comment by Barno** [comment]
presa in carica in ita

**Comment by Barno** [comment]
presa in carica in eng
