### ISSUE TITLE
[199] Domanda 175 - verofalso

### ISSUE THREAD

**Issue by alessandro-aglietti** [bitcoin-dalla-teoria-alla-pratica/errata-corrige-e-sorgente-esempi#79]
*Che tipo di segnalazione stai facendo?*
- [ ] Errore
- [X] Modifica

*Quale e' la versione della risposta che proponi?*
[...]blocchi **arbitrari senza consenso**

**Comment by Barno** [comment]
presa in carico in italiano

**Comment by Barno** [comment]
presa in carico in eng
