### ISSUE TITLE
[199] Domanda 180 - elliticismo

### ISSUE THREAD

**Issue by alessandro-aglietti** [bitcoin-dalla-teoria-alla-pratica/errata-corrige-e-sorgente-esempi#80]
*Che tipo di segnalazione stai facendo?*
- [ ] Errore
- [X] Modifica

*Quale e' la versione della risposta che proponi?*
[...]statiche **della curva ellittica**[...]
[...]chiavi **usate in ECDSA**

**Comment by Barno** [comment]
presa in carico in ITA

**Comment by Barno** [comment]
presa in carico in eng
