### ISSUE TITLE
[199] Domanda 181 - ellitiscettismo

### ISSUE THREAD

**Issue by alessandro-aglietti** [bitcoin-dalla-teoria-alla-pratica/errata-corrige-e-sorgente-esempi#81]
*Che tipo di segnalazione stai facendo?*
- [ ] Errore
- [X] Modifica

*Quale e' la versione della risposta che proponi?*
[...]ellittica **Secp256k1, utilizzate per generarla.**

**Comment by Barno** [comment]
presa in carico in italiano

**Comment by Barno** [comment]
presa in carico eng
