### ISSUE TITLE
[199] Domanda 190 - sicuramente proforma

### ISSUE THREAD

**Issue by alessandro-aglietti** [bitcoin-dalla-teoria-alla-pratica/errata-corrige-e-sorgente-esempi#84]
*Che tipo di segnalazione stai facendo?*
- [ ] Errore
- [X] Modifica

*Quale e' la versione della risposta che proponi?*
[...]SPV**, quando si richiede informazioni,**

**Comment by Barno** [comment]
...Vengono utilizzati dai nodi SPV, quando richiedono informazioni...
Presa in carico in italiano
