### ISSUE TITLE
[199] Domanda 191 - digEstivo

### ISSUE THREAD

**Issue by alessandro-aglietti** [bitcoin-dalla-teoria-alla-pratica/errata-corrige-e-sorgente-esempi#85]
*Che tipo di segnalazione stai facendo?*
- [ ] Errore
- [X] Modifica

*Quale e' la versione della risposta che proponi?*
output > digest
[...]perche' e' **altamente improbabile**

**Comment by Barno** [comment]
Presa in carico per l'italiano

**Comment by Barno** [comment]
Presa in carico per ENG
