### ISSUE TITLE
[199] Domanda 192 - hascelle

### ISSUE THREAD

**Issue by alessandro-aglietti** [bitcoin-dalla-teoria-alla-pratica/errata-corrige-e-sorgente-esempi#86]
*Che tipo di segnalazione stai facendo?*
- [ ] Errore
- [X] Modifica

*Quale e' la versione della risposta che proponi?*
No, **in una funzione di hash, **[...]

**Comment by Barno** [comment]
Presa in carico per l'italiano

**Comment by Barno** [comment]
presa in carico per l'inglese
