### ISSUE TITLE
[199] Domanda 195 - OP_RETURN siamo sicuri che rende non spendibile l'UTXO?

### ISSUE THREAD

**Issue by alessandro-aglietti** [bitcoin-dalla-teoria-alla-pratica/errata-corrige-e-sorgente-esempi#87]
*Che tipo di segnalazione stai facendo?*
- [ ] Errore
- [X] Modifica

Prima di usare OP_RETURN si scriveva l'hex del messaggio al posto del P2PKH rendendo l'UTXO non spendibile.
Poi ci siamo fatti furbi ed abbiamo iniziato ad utilizzare OP_RETURN.

**Comment by Barno** [comment]
L'informazione dettagliata compresa delle modifiche fatte alle versioni del Database è dentro a Bitcoin dalla teoria alla pratica. 
Si deve spiegare in quale porzioni di bytes si scriveva prima, rischia di essere una informazione incompleta
si siamo sicuri al 101% che rende la utxo inspendibile.
