### ISSUE TITLE
[199] Ordinare i rigranziamenti per cognome alfabetico

### ISSUE THREAD

**Issue by alessandro-aglietti** [bitcoin-dalla-teoria-alla-pratica/errata-corrige-e-sorgente-esempi#88]
Altrimenti non e' abbastanza ordinato

**Comment by Barno** [comment]
Sono ordinati in base al contributo dato, consigli ugualmente la modifica?

**Comment by Barno** [comment]
Presa in carico per l'italiano, aggiungere traduttrice in inglese
