### ISSUE TITLE
[199] Domanda 53/73/77 - una transazione

### ISSUE THREAD

**Issue by alessandro-aglietti** [bitcoin-dalla-teoria-alla-pratica/errata-corrige-e-sorgente-esempi#9]
*Che tipo di segnalazione stai facendo?*
- [ ] Errore
- [X] Modifica

*Quale e' la versione della domanda che proponi?*
Come posso verificare **una** transazione?
Posso annullare **una** transazione?
Come si raggiunge il consenso **di una** transazione?

**Comment by Barno** [comment]
La domanda è rivolta al lettore che è alle prese con la sua prima transazione. Infatti nella risposta si trova "...Solitamente i software wallet..." come se lo avesse davanti.
