### ISSUE TITLE
[LIBRO] Pagina 28 - Uso di file (.txt) mai creato

### ISSUE THREAD

**Issue by wildnet2** [bitcoin-dalla-teoria-alla-pratica/errata-corrige-e-sorgente-esempi#95]
Quale frase contiene l'errore?

Il comando shell 
```
openssl dgst -sha256 -sign private.pem testo_segreto.txt > signature.bin
```
fa uso del file di testo `testo_segreto.txt` mai creato precedentemente

Quale versione corretta proponi?

Aggiungerei il comando
```
touch testo_segreto.txt 
```

**Comment by Barno** [comment]
Implementato nella prossima release
