### ISSUE TITLE
[LIBRO] Pagina 52 - Comando per invertire l'ordine dei byte incompleto

### ISSUE THREAD

**Issue by wildnet2** [bitcoin-dalla-teoria-alla-pratica/errata-corrige-e-sorgente-esempi#96]
Quale frase contiene l'errore?

Il comando 
```
printf 50120119172a610421a6c3011dd330d9df07b63616c2cc1f1cd0020000000000 | tac  -rc
```
non è corretto (mancano i due punti).

Quale versione corretta proponi?

Modificare con il comando corretto

```
printf 50120119172a610421a6c3011dd330d9df07b63616c2cc1f1cd0020000000000 | tac  -rc ..

```

**Comment by Barno** [comment]
`printf 50120119172a610421a6c3011dd330d9df07b63616c2cc1f1cd0020000000000 | tac -rs ..`
